USE canvas;
SELECT
account_dim.name AS "Account Name"
, account_dim.workflow_state AS "Account Status"
, enrollment_term_dim.name AS "Term Name"
, enrollment_term_dim.date_start AS "Term Start On"
, enrollment_term_dim.date_end AS "Term Ends On"
, course_section_dim.name AS "Course Section Name"
, course_section_dim.accepting_enrollments AS "Course Section Accepting Enrollments"
, course_section_dim.can_manually_enroll AS "Course Section Can Manually Enroll"
, course_section_dim.created_at AS "Course Section Created At"
, course_section_dim.default_section AS "Course Section Default Section"
, course_section_dim.end_at AS "Course Section End At"
, course_section_dim.restrict_enrollments_to_section_dates AS "Course Section Restrict Enrollments to Section Dates"
, course_section_dim.start_at AS "Course Section Start At"
, course_section_dim.updated_at AS "Course Section Updated At"
, course_section_dim.workflow_state AS "Course Section State"
, course_dim.sis_source_id As "Course SIS"
, course_dim.code AS "Course Catalog"
, course_dim.name AS "Course Name"
, course_dim.created_at AS "Course Created At"
, course_dim.start_at AS "Course Started At"
, course_dim.conclude_at AS "Course Concluded At"
, course_dim.workflow_state AS "Course State"
, group_dim.category AS "Group Category"
, group_dim.context_type AS "Group Type"
, group_dim.created_at AS "Group Created At"
, group_dim.default_view AS "Group Default View"
, group_dim.deleted_at AS "Group Deleted At"
, group_dim.name AS "Group Name"
, group_dim.updated_at AS "Group Updated At"
, group_dim.workflow_state AS "Group State"
, assignment_group_dim.created_at AS "Assignment Group Created At"
, assignment_group_dim.default_assignment_name AS "Assignment Group Default Assignment Name"
, assignment_group_dim.name AS "Assignment Group Name"
, assignment_group_dim.position AS "Assignment Group Position"
, assignment_group_dim.updated_at AS "Assignment Group Updated At"
, assignment_group_dim.workflow_state AS "Assignment Group State"
, assignment_dim.submission_types AS "Assignment Submission Type"
, assignment_dim.title AS "Assignment Title"
, assignment_dim.description AS "Assignment Description"
, assignment_dim.created_at AS "Assignment Created At"
, assignment_dim.all_day AS "Assignment All Day Due"
, assignment_dim.all_day_date AS "Assignment All Day Due Date"
, assignment_dim.due_at AS "Assignment Due At"
, assignment_dim.peer_reviews_due_at AS "Assignment Peer Reviews Due At"
, assignment_dim.updated_at AS "Assignment Updated At"
, assignment_dim.could_be_locked AS "Assignment Could Be Locked"
, assignment_dim.lock_at AS "Assignment Locked At"
, assignment_dim.unlock_at AS "Assignment Unlock At"
, assignment_dim.peer_reviews AS "Assignment Peer Reviews"
, assignment_dim.automatic_peer_reviews AS "Assignment Peer Review Automatically Assigned"
, assignment_dim.peer_review_count AS "Assignment Peer Reviewers Count"
, assignment_dim.grading_type AS "Assignment Grading Type"
, assignment_dim.points_possible AS "Assignment Possible Points"
, assignment_dim.grade_group_students_individually AS "Assignment Group Individually Graded"
, assignment_dim.visibility AS "Assignment Visibility"
, assignment_dim.position AS "Assignment Position"
, assignment_dim.workflow_state AS "Assignment State"
, quiz_dim.name AS "Quiz Name"
, quiz_dim.description AS "Quiz Description"
, quiz_dim.quiz_type AS "Quiz Type"
, quiz_dim.created_at AS "Quiz Created At"
, quiz_dim.published_at AS "Quiz Published At"
, quiz_dim.updated_at AS "Quiz Updated At"
, quiz_dim.due_at AS "Quiz Due At"
, quiz_dim.hide_correct_answers_at AS "Quiz Hide Correct Answers At"
, quiz_dim.could_be_locked AS "Quiz Could Be Locked"
, quiz_dim.lock_at AS "Quiz Lock At"
, quiz_dim.unlock_at AS "Quiz Unlock At"
, quiz_dim.show_correct_answers AS "Quiz Show Correct Answers"
, quiz_dim.show_correct_answers_at AS "Quiz Show Correct Answers At"
, quiz_dim.deleted_at AS "Quiz Deleted At"
, quiz_dim.anonymous_submissions AS "Quiz Anonymous Submission"
, quiz_dim.answer_display_order AS "Quiz Answer Display Order"
, quiz_dim.browser_lockdown AS "Quiz Browser Lockdown"
, quiz_dim.browser_lockdown_for_displaying_results AS "Quiz Browser Lockdown for Displaying Results"
, quiz_dim.browser_lockdown_monitor AS "Quiz Lockdown Monitor"
, quiz_dim.display_questions AS "Quiz Display Questions"
, quiz_dim.go_back_to_previous_question AS "Quiz Go Back to Previous Question"
, quiz_dim.ip_filter AS "Quiz IP Filter"
, quiz_dim.scoring_policy AS "Quiz Scoring Policy"
, quiz_dim.show_results AS "Quiz Show Results"
, quiz_dim.points_possible AS "Quiz Points Possible"
, quiz_dim.workflow_state AS "Quiz State"
, assignment_override_dim.all_day AS "Assignment Override All Day"
, assignment_override_dim.all_day_date AS "Assignment Override All Day Date"
, assignment_override_dim.assignment_version AS "Assignment Override Version"
, assignment_override_dim.created_at AS "Assignment Override Created At"
, assignment_override_dim.due_at AS "Assignment Override Due At"
, assignment_override_dim.due_at_overridden AS "Assignment Due At Overridden"
, assignment_override_dim.lock_at AS "Assignment Override Locked At"
, assignment_override_dim.lock_at_overridden AS "Assignment Override Locked At Overridden"
, assignment_override_dim.quiz_version AS "Assignment Override Quiz Version"
, assignment_override_dim.set_type AS "Assignment Override Set Type"
, assignment_override_dim.title AS "Assignment Override Title"
, assignment_override_dim.unlock_at AS "Assignment Override Unlock At"
, assignment_override_dim.unlock_at_overridden AS "Assignment Override Unlock At Overridden"
, assignment_override_dim.updated_at AS "Assignment Override Updated At"
, assignment_override_dim.workflow_state AS "Assignment Overriding State"
FROM assignment_override_fact
JOIN account_dim ON account_dim.id = assignment_override_fact.account_id
JOIN course_dim ON course_dim.id = assignment_override_fact.course_id
JOIN enrollment_term_dim ON enrollment_term_dim.id = assignment_override_fact.enrollment_term_id
LEFT JOIN group_dim ON group_dim.id = assignment_override_fact.group_id
LEFT JOIN quiz_dim ON quiz_dim.id = assignment_override_fact.quiz_id
LEFT JOIN assignment_group_dim ON assignment_group_dim.id = assignment_override_fact.assignment_group_id
LEFT JOIN assignment_dim ON assignment_dim.id = assignment_override_fact.assignment_id
LEFT JOIN assignment_override_dim ON assignment_override_dim.id = assignment_override_fact.assignment_override_id
LEFT JOIN course_section_dim ON course_section_dim.id = assignment_override_fact.course_section_id
WHERE account_dim.name = "Fuller Theological Seminary"
AND account_dim.workflow_state != "deleted"
AND enrollment_term_dim.name NOT IN ("All Other Courses", "Course Development (DL)", "Course Development (Faculty)", "Default Term", "Fuller Canvas Templates", "Orientation 2017", "Orientation 2018", "Orientation 2019", "Orientation 2020")
AND course_dim.workflow_state != "deleted"
AND course_dim.sis_source_id IS NOT NULL
AND assignment_dim.workflow_state NOT IN ("unpublished", "deleted")
AND quiz_dim.workflow_state != "unpublished"
;