USE canvas;
SELECT 
enrollment_term_dim.name AS "Term Name"
, enrollment_term_dim.date_start AS "Term Start On"
, enrollment_term_dim.date_end AS "Term Ends On"
, course_dim.sis_source_id As "Course SIS"
, course_dim.code AS "Course Catalog"
, course_dim.name AS "Course Name"
, course_dim.created_at AS "Course Created At"
, course_dim.start_at AS "Course Started At"
, course_dim.conclude_at AS "Course Concluded At"
, course_dim.workflow_state AS "Course State"
, assignment_dim.submission_types AS "Assignment Submission Type"
, assignment_dim.title AS "Assignment Title"
, assignment_dim.description AS "Assignment Description"
, assignment_dim.created_at AS "Assignment Created At"
, assignment_dim.all_day AS "Assignment All Day Due"
, assignment_dim.all_day_date AS "Assignment All Day Due Date"
, assignment_dim.due_at AS "Assignment Due At"
, assignment_dim.peer_reviews_due_at AS "Assignment Peer Reviews Due At"
, assignment_dim.updated_at AS "Assignment Updated At"
, assignment_dim.could_be_locked AS "Assignment Could Be Locked"
, assignment_dim.lock_at AS "Assignment Locked At"
, assignment_dim.unlock_at AS "Assignment Unlock At"
, assignment_dim.peer_reviews AS "Assignment Peer Reviews"
, assignment_dim.automatic_peer_reviews AS "Assignment Peer Review Automatically Assigned"
, assignment_dim.peer_review_count AS "Assignment Peer Reviewers Count"
, assignment_dim.grading_type AS "Assignment Grading Type"
, assignment_dim.points_possible AS "Assignment Possible Points"
, assignment_dim.grade_group_students_individually AS "Assignment Group Individually Graded"
, assignment_dim.visibility AS "Assignment Visibility"
, assignment_dim.position AS "Assignment Position"
, assignment_dim.workflow_state AS "Assignment State"
, submission_dim.attempt AS "Submission Attempt"
, submission_dim.body AS "Submission Body"
, submission_dim.created_at AS "Submission Created At"
, submission_dim.excused AS "Submission Excused"
, submission_dim.grade AS "Submission Grade"
, submission_dim.grade_matches_current_submission AS "Submission Grade Matches Current Submission"
, submission_dim.grade_state AS "Submission Grade State"
, submission_dim.graded_anonymously AS "Submission Grade Anonymously"
, submission_dim.graded_at AS "Submission Graded At"
, submission_dim.has_admin_comment AS "Submission Has Admin Comment"
, submission_dim.has_rubric_assessment AS "Submission Has Rubric Assessment"
, submission_dim.posted_at AS "Submission Posted At"
, submission_dim.process_attempts AS "Submission Process Attempts"
, submission_dim.processed AS "Submission Processed"
, submission_dim.published_grade AS "Submission Published Grade"
, submission_dim.submission_type AS "Submission Type"
, submission_dim.submitted_at AS "Submission Submitted At"
, submission_dim.updated_at AS "Submission Updated At"
, submission_dim.url AS "Submission URL"
, submission_dim.workflow_state AS "Submission State"
, submission_comment_dim.hidden AS "Submission Comment Is Hidden"
, submission_comment_dim.anonymous AS "Submission Comment Anonymous"
, submission_comment_dim.author_name AS "Submission Comment Author Name"
, submission_comment_dim.comment AS "Submission Comment"
, submission_comment_dim.teacher_only_comment AS "Submission Teacher Only Comment"
, submission_comment_dim.created_at AS "Submission Comment Created At"
, submission_comment_dim.updated_at AS "Submission Comment Updated At"
, submission_comment_fact.message_size_bytes AS "Submission Comment Size Bytes"
, submission_comment_fact.message_line_count AS "Submission Comment Line Count"
, submission_comment_fact.message_word_count AS "Submission Comment Word Count"
, submission_comment_fact.message_character_count AS "Submission Comment Character Count"
FROM submission_comment_fact
INNER JOIN assignment_dim ON assignment_dim.id = submission_comment_fact.assignment_id
INNER JOIN course_dim ON course_dim.id = submission_comment_fact.course_id
INNER JOIN enrollment_term_dim ON enrollment_term_dim.id = submission_comment_fact.enrollment_term_id
INNER JOIN submission_comment_dim ON submission_comment_dim.id = submission_comment_fact.submission_comment_id 
INNER JOIN submission_dim ON submission_dim.id = submission_comment_fact.submission_id;