USE canvas;
SELECT 
enrollment_term_dim.name AS "Term Name"
, enrollment_term_dim.date_start AS "Term Start On"
, enrollment_term_dim.date_end AS "Term Ends On"
, course_dim.sis_source_id As "Course SIS"
, course_dim.code AS "Course Catalog"
, course_dim.name AS "Course Name"
, course_dim.created_at AS "Course Created At"
, course_dim.start_at AS "Course Started At"
, course_dim.conclude_at AS "Course Concluded At"
, course_dim.workflow_state AS "Course State"
, assignment_dim.submission_types AS "Assignment Submission Type"
, assignment_dim.title AS "Assignment Title"
, assignment_dim.description AS "Assignment Description"
, assignment_dim.created_at AS "Assignment Created At"
, assignment_dim.all_day AS "Assignment All Day Due"
, assignment_dim.all_day_date AS "Assignment All Day Due Date"
, assignment_dim.due_at AS "Assignment Due At"
, assignment_dim.peer_reviews_due_at AS "Assignment Peer Reviews Due At"
, assignment_dim.updated_at AS "Assignment Updated At"
, assignment_dim.could_be_locked AS "Assignment Could Be Locked"
, assignment_dim.lock_at AS "Assignment Locked At"
, assignment_dim.unlock_at AS "Assignment Unlock At"
, assignment_dim.peer_reviews AS "Assignment Peer Reviews"
, assignment_dim.automatic_peer_reviews AS "Assignment Peer Review Automatically Assigned"
, assignment_dim.peer_review_count AS "Assignment Peer Reviewers Count"
, assignment_dim.grading_type AS "Assignment Grading Type"
, assignment_dim.points_possible AS "Assignment Possible Points"
, assignment_dim.grade_group_students_individually AS "Assignment Group Individually Graded"
, assignment_dim.visibility AS "Assignment Visibility"
, assignment_dim.position AS "Assignment Position"
, assignment_dim.workflow_state AS "Assignment State"
, submission_dim.attempt AS "Submission Attempt"
, submission_dim.body AS "Submission Body"
, submission_dim.created_at AS "Submission Created At"
, submission_dim.excused AS "Submission Excused"
, submission_dim.grade AS "Submission Grade"
, submission_dim.grade_matches_current_submission AS "Submission Grade Matches Current Submission"
, submission_dim.grade_state AS "Submission Grade State"
, submission_dim.graded_anonymously AS "Submission Grade Anonymously"
, submission_dim.graded_at AS "Submission Graded At"
, submission_dim.has_admin_comment AS "Submission Has Admin Comment"
, submission_dim.has_rubric_assessment AS "Submission Has Rubric Assessment"
, submission_dim.posted_at AS "Submission Posted At"
, submission_dim.process_attempts AS "Submission Process Attempts"
, submission_dim.processed AS "Submission Processed"
, submission_dim.published_grade AS "Submission Published Grade"
, submission_dim.submission_type AS "Submission Type"
, submission_dim.submitted_at AS "Submission Submitted At"
, submission_dim.updated_at AS "Submission Updated At"
, submission_dim.url AS "Submission URL"
, submission_dim.workflow_state AS "Submission State"
, user_dim.name AS "User Name"
, user_dim.gender AS "User Gender"
, user_dim.birthdate AS "User Birthdate"
, user_dim.school_name AS "User School"
, user_dim.school_position AS "User School Position"
, user_dim.country_code AS "User Country"
, user_dim.locale AS "User locale"
, user_dim.time_zone AS "User Time Zone"
, user_dim.created_at AS "User Created At"
, user_dim.workflow_state AS "User Status"
, file_dim.content_type AS "File Content Type"
, file_dim.could_be_locked AS "File Could Be Locked"
, file_dim.created_at AS "File Created At"
, file_dim.deleted_at AS "File Deleted At"
, file_dim.display_name AS "File Display Name"
, file_dim.file_state AS "File State"
, file_dim.lock_at AS "File Lock At"
, file_dim.locked AS "File Locked"
, file_dim.md5 AS "File MD5"
, file_dim.owner_entity_type AS "File Owner Entity Type"
, file_dim.unlock_at AS "File Unlock At"
, file_dim.updated_at AS "File Updated At"
, file_dim.viewed_at AS "File Viewed At"
FROM submission_file_fact
INNER JOIN assignment_dim ON assignment_dim.id = submission_file_fact.assignment_id
INNER JOIN course_dim ON course_dim.id = submission_file_fact.course_id
INNER JOIN enrollment_term_dim ON enrollment_term_dim.id = submission_file_fact.enrollment_term_id
INNER JOIN file_dim ON file_dim.id = submission_file_fact.file_id
INNER JOIN submission_dim ON submission_dim.id = submission_file_fact.submission_id
INNER JOIN user_dim ON user_dim.id = submission_file_fact.user_id
-- LEFT OUTER JOIN grader_dim ON grader_dim.id = submission_file_fact.grader_id
;